#!/bin/sh
# You might need to make this executable using:
# $ chmod +x git_hooks/pre-commit

# see https://stackoverflow.com/a/5947802/1892669
RED='\033[0;31m'
YELLOW='\033[1;33m'
GREEN='\033[0;32m'
NC='\033[0m' # No Color

# prevent developers from committing directly to `main`
branch="$(git rev-parse --abbrev-ref HEAD)"
if [ "$branch" = "main" ]; then
  echo -e "${YELLOW}Oy!${NC} Please don't commit directly to the \"main\" branch. Make a pull request instead:"
  echo -e "  ${GREEN}$ git checkout -b \"dev\"${NC}"
  echo -e "  ${GREEN}$ git commit -m \"my message\" -m \"a longer description\"${NC}"
  echo -e "  ${GREEN}$ git push${NC}"
  exit 1
fi

# format code before committing it
if ! type "$black" > /dev/null; then
  echo "Please make sure you have the \"black\" code formatter on your path."
  exit 1
fi

if ! black --quiet --check .; then
  echo "Running \"black --quiet .\" to format code.";
  black --quiet .
fi
